# Generated by Django 4.1 on 2022-08-23 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 8, 23, 8, 29, 43, 699054, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
