# Generated by Django 4.1 on 2022-08-23 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
