# Generated by Django 4.1 on 2022-08-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=150, unique_for_date="publish_date"),
        ),
    ]
