# Generated by Django 4.1 on 2022-08-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="article",
            name="publish_date",
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
