# Generated by Django 4.1 on 2022-08-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_remove_article_publish_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("des", models.TextField()),
            ],
        ),
    ]
