# Generated by Django 4.1 on 2022-08-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_newtest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewTest",
        ),
    ]
