# Generated by Django 4.1 on 2022-08-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_delete_newtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
