# Generated by Django 4.1 on 2022-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_article_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/articles"),
        ),
    ]
