# Generated by Django 4.1 on 2022-08-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
