# Generated by Django 4.1 on 2022-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_article_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("id",)},
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(related_name="articles", to="blog.category"),
        ),
    ]
