# Generated by Django 4.1 on 2022-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish_at",
            field=models.DateTimeField(null=True),
        ),
    ]
