# Generated by Django 4.1 on 2022-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_message_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterField(
            model_name="message",
            name="cretaed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="message",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Sender Email"),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Read"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
    ]
